"use client";
import dynamic from 'next/dynamic';
import Link from 'next/link';
import {useMemo,useState} from 'react';
import {useSearchParams,useRouter} from 'next/navigation';
import {Search,Map,LayoutGrid,ArrowUpRight,MapPin,X} from 'lucide-react';
import {filterCompanies,parseFilters} from '@/lib/catalog/filters';
import type {Company} from '@/lib/catalog/types';
const ChennaiMap=dynamic(()=>import('./chennai-map'),{ssr:false,loading:()=> <div className="map-loading">Loading Chennai map…</div>});
export function Directory({companies,hiringSlugs=[]}:{companies:Company[];hiringSlugs?:string[]}){
 const params=useSearchParams();const router=useRouter();const filters=parseFilters(params);const mode=params.get('view')==='grid'?'grid':'map';const [selected,setSelected]=useState('');
 const filtered=useMemo(()=>filterCompanies(companies,parseFilters(new URLSearchParams(params.toString())),hiringSlugs),[companies,params,hiringSlugs]);
 function update(key:string,value:string){const next=new URLSearchParams(params.toString());if(value)next.set(key,value);else next.delete(key);router.replace('/?'+next.toString(),{scroll:false});}
 const picked=companies.find(c=>c.slug===selected);
 return <><div className="discovery-controls"><label className="directory-search"><Search size={19}/><input aria-label="Search companies" placeholder="Search companies, sectors, or neighbourhoods…" value={filters.query} onChange={e=>update('q',e.target.value)}/>{filters.query&&<button aria-label="Clear search" onClick={()=>update('q','')}><X size={15}/></button>}</label><div className="view-switch" aria-label="Display mode"><button aria-pressed={mode==='map'} onClick={()=>update('view','map')}><Map size={16}/>Map</button><button aria-pressed={mode==='grid'} onClick={()=>update('view','grid')}><LayoutGrid size={16}/>Grid</button></div></div>
 <div className="filter-row">{(['sector','area','kind'] as const).map(key=><label key={key}><span>{key==='kind'?'Company type':key==='area'?'Neighbourhood':'Sector'}</span><select value={filters[key]} onChange={e=>update(key,e.target.value)}><option value="">All {key==='kind'?'types':key==='area'?'neighbourhoods':'sectors'}</option>{[...new Set(companies.map(c=>c[key]))].sort().map(value=><option key={value}>{value}</option>)}</select></label>)}<label className="hiring-filter"><input type="checkbox" checked={filters.hiring} onChange={e=>update('hiring',e.target.checked?'1':'')}/>With listed jobs</label>{Object.values(filters).some(Boolean)&&<button className="clear-filters" onClick={()=>router.replace('/?view='+mode,{scroll:false})}>Clear filters</button>}</div>
 <div className="directory-heading"><h2 aria-live="polite">{filtered.length} {filtered.length===1?'company':'companies'} to discover</h2><span>Chennai & its startup corridor</span></div>
 <div className={mode==='map'?'map-discovery':'grid-discovery'}><div className={mode==='grid'?'directory-grid':'map-company-list'}>{filtered.map(c=><article key={c.slug} className={'directory-card '+(selected===c.slug?'selected-card':'')}><span className="company-initial">{c.name.slice(0,2).toUpperCase()}</span><span className="sector-badge">{c.sector}</span><h2><Link href={'/company/'+c.slug}>{c.name}</Link></h2><p>{c.description}</p><div className="directory-card-bottom"><button className="location-select" onClick={()=>{setSelected(c.slug);update('view','map')}}><MapPin size={14}/>{c.area}</button><Link href={'/company/'+c.slug}>Explore <ArrowUpRight size={15}/></Link></div></article>)}{!filtered.length&&<div className="empty-state"><h2>No companies match these filters.</h2><p>Try another neighbourhood or clear a filter.</p></div>}</div>{mode==='map'&&<div className="map-column"><ChennaiMap companies={filtered} onSelect={setSelected}/><div className="map-caption">{filtered.filter(c=>c.latitude!==null).length} mapped · Area markers are approximate. Unverified locations stay in the list.</div>{picked&&<aside className="map-selection"><button aria-label="Close company selection" onClick={()=>setSelected('')}><X size={16}/></button><b>{picked.name}</b><p>{picked.address}</p><Link href={'/company/'+picked.slug}>Explore company <ArrowUpRight size={14}/></Link></aside>}</div>}</div></>;
}
